openapi: 3.1.0
info:
  title: Contacts API
  summary: API used to manage contacts.
  description: This API is ...
  termsOfService: https://example.com/terms
  contact:
    name: Humberto Corrêa da Silva
    url: https://github.com/humbertoc-silva
    email: humberto@example.com
  license:
    name: MIT
    url: https://github.com/humbertoc-silva/contacts-api/blob/main/LICENSE
  version: 1.0.0
jsonSchemaDialect: https://spec.openapis.org/oas/3.1/dialect/base
servers:
  - url: https://localhost:8443/contacts/v1
    description: Local server.
  - url: https://{environment}.example.com/contacts/v1
    description: Development and staging server.
    variables:
      environment:
        enum:
          - development
          - staging
        default: development
        descriptions: Server's environment.
  - url: http://example.com/contacts/v1
    descriptions: Production server.
paths:
  /contacts:
    summary: ...
    description: ...
    
    get:
      tags:
        - contacts
      summary: ...
      description: ...
      externalDocs:
        description: ...
        url: https://example.com/docs/contacts/v1/contacts/get
      operationId: getContacts
    
    post:
      tags:
        - contacts
      summary: ...
      description: ...
      externalDocs:
        description: ...
        url: https://example.com/docs/contacts/v1/contacts/post
      operationId: postContacts
  
  /contacts/{contactId}:
    summary: ...
    description: ...
    
    get:
      tags:
        - contacts
      summary: ...
      description: ...
      externalDocs:
        description: ...
        url: https://example.com/docs/contacts/v1/contacts/{contactId}/get
      operationId: getContact
    
    put:
      tags:
        - contacts
      summary: ...
      description: ...
      externalDocs:
        description: ...
        url: https://example.com/docs/contacts/v1/contacts/{contactId}/put
      operationId: putContact
    
    delete:
      tags:
        - contacts
      summary: ...
      description: ...
      externalDocs:
        description: ...
        url: https://example.com/docs/contacts/v1/contacts/{contactId}/delete
      operationId: deleteContact

    patch:
      tags:
        - contacts
      summary: ...
      description: ...
      externalDocs:
        description: ...
        url: https://example.com/docs/contacts/v1/contacts/{contactId}/patch
      operationId: patchContact
  
    parameters:
      - $ref: '#/components/parameters/contactId'

  /contacts/{contactId}/phones:
    summary: ...
    description: ...
    
    get:
      tags:
        - contact-phones
      summary: ...
      description: ...
      externalDocs:
        description: ...
        url: https://example.com/docs/contacts/v1/contacts/{contactId}/phones/get
      operationId: getContactPhones
    
    post:
      tags:
        - contact-phones
      summary: ...
      description: ...
      externalDocs:
        description: ...
        url: https://example.com/docs/contacts/v1/contacts/{contactId}/phones/post
      operationId: postContactPhones
  
    parameters:
      - $ref: '#/components/parameters/contactId'
    
  /contacts/{contactId}/phones/{phoneId}:
    summary: ...
    description: ...
    
    get:
      tags:
        - contact-phones
      summary: ...
      description: ...
      externalDocs:
        description: ...
        url: https://example.com/docs/contacts/v1/contacts/{contactId}/phones/{phoneId}/get
      operationId: getContactPhone
    
    put:
      tags:
        - contact-phones
      summary: ...
      description: ...
      externalDocs:
        description: ...
        url: https://example.com/docs/contacts/v1/contacts/{contactId}/phones/{phoneId}/put
      operationId: putContactPhone
    
    delete:
      tags:
        - contact-phones
      summary: ...
      description: ...
      externalDocs:
        description: ...
        url: https://example.com/docs/contacts/v1/contacts/{contactId}/phones/{phoneId}/delete
      operationId: deleteContactPhone

    patch:
      tags:
        - contact-phones
      summary: ...
      description: ...
      externalDocs:
        description: ...
        url: https://example.com/docs/contacts/v1/contacts/{contactId}/phones/{phoneId}/patch
      operationId: patchContactPhone
  
    parameters:
      - $ref: '#/components/parameters/contactId'
      - $ref: '#/components/parameters/phoneId'

  /contacts/{contactId}/emails:
    summary: ...
    description: ...
    
    get:
      tags:
        - contact-email
      summary: ...
      description: ...
      externalDocs:
        description: ...
        url: https://example.com/docs/contacts/v1/contacts/{contactId}/emails/get
      operationId: getContactEmails
    
    post:
      tags:
        - contact-email
      summary: ...
      description: ...
      externalDocs:
        description: ...
        url: https://example.com/docs/contacts/v1/contacts/{contactId}/emails/post
      operationId: postContactEmails
  
    parameters:
      - $ref: '#/components/parameters/contactId'

  /contacts/{contactId}/emails/{emailId}:
    summary: ...
    description: ...
    
    get:
      tags:
        - contact-email
      summary: ...
      description: ...
      externalDocs:
        description: ...
        url: https://example.com/docs/contacts/v1/contacts/{contactId}/emails/{emailId}/get
      operationId: getContactEmail
    
    put:
      tags:
        - contact-email
      summary: ...
      description: ...
      externalDocs:
        description: ...
        url: https://example.com/docs/contacts/v1/contacts/{contactId}/emails/{emailId}/put
      operationId: putContactEmail
    
    delete:
      tags:
        - contact-email
      summary: ...
      description: ...
      externalDocs:
        description: ...
        url: https://example.com/docs/contacts/v1/contacts/{contactId}/emails/{emailId}/delete
      operationId: deleteContactEmail
    
    patch:
      tags:
        - contact-email
      summary: ...
      description: ...
      externalDocs:
        description: ...
        url: https://example.com/docs/contacts/v1/contacts/{contactId}/emails/{emailId}/patch
      operationId: patchContactEmail

    parameters:
      - $ref: '#/components/parameters/contactId'
      - $ref: '#/components/parameters/emailId'

components:
  parameters:
    contactId:
      name: contactId
      in: path
      description: ...
      required: true
      schema:
        type: integer
        format: int64
      example: 1
    phoneId:
      name: phoneId
      in: path
      description: ...
      required: true
      schema:
        type: integer
        format: int64
      example: 1
    emailId:
      name: phoneId
      in: path
      description: ...
      required: true
      schema:
        type: integer
        format: int64
      example: 1